from enum import Enum
from typing import Any, Protocol, runtime_checkable


class AnimationStyle(Enum):
    EXPRESSIVE = 1
    EXPLANATORY = 2


@runtime_checkable
class DeviceAdapter(Protocol):
    def setup(self, logger: Any) -> None: ...
    def get_mic(self) -> Any | None: ...
    def play_audio_bytes(self, audio_bytes: bytes, sample_rate: int) -> None: ...
    def say_natively(self, text: str, language: str = "en", animated: bool = False) -> None: ...
    def play_animation(self, animation_name: str, run_async: bool = False) -> None: ...
    def play_speaking_animation(self, style: AnimationStyle) -> None: ...
    def play_motion_sequence(self, file_path: str) -> None: ...
    def set_leds(self, r: float = 0, g: float = 0, b: float = 0, name: str = "FaceLeds") -> None: ...
    def signal_listening(self, start: bool = True) -> None: ...
    def disconnect(self) -> None: ...